# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: (c) 2026 Yiltan Temucin <yiltan.temucin@gmail.com>

bin_PROGRAMS = hello fi_getinfo
hello_SOURCES = main.c
hello_CFLAGS = $(LIBFABRIC_CFLAGS)
hello_LDADD = $(LIBFABRIC_LIBS)
fi_getinfo_SOURCES = fi_getinfo.c
fi_getinfo_CFLAGS = $(LIBFABRIC_CFLAGS)
fi_getinfo_LDADD = $(LIBFABRIC_LIBS)
